sd/sd/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("swexplorer:list")), name="index"),
    path("collection/", include("swexplorer.urls")),
]

sd/swexplorer/urls.py
from django.urls import path
from swexplorer import views

app_name = "swexplorer"
urlpatterns = [
    path("", views.CollectionListView.as_view(), name="list"),
    path("fetch/", views.FetchCollectionView.as_view(), name="fetch"),
    path("<int:pk>/", views.CollectionDetailView.as_view(), name="detail"),
    path("<int:pk>/count/", views.CollectionCountView.as_view(), name="count"),
]

sd/swexplorer/models.py
import uuid
from tempfile import NamedTemporaryFile

import petl as etl
from django.core.files import File
from django.db import models
from django.urls import reverse
from petl import datetimeparser

from swexplorer.client import SWClient

isodatetime = datetimeparser("%Y-%m-%dT%H:%M:%S.%f%z")


class Collection(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to="swexplorer/collection/file")

    class Meta:
        ordering = ["-created"]

    def get_absolute_url(self):
        return reverse("swexplorer:detail", kwargs={"pk": self.pk})

    @property
    def etl(self):
        return etl.fromcsv(self.file.path)

    @classmethod
    def get_collection(cls):
        people, homeworlds = cls.fetch_starwars_data()

        people_table = etl.fromdicts(people)
        homeworlds_table = etl.fromdicts(homeworlds)
        homeworlds_table = homeworlds_table.cutout(*range(1, 13))
        homeworlds_table = homeworlds_table.rename("name", "homeworld_name")
        people_table = people_table.join(homeworlds_table, lkey="homeworld", rkey="url")
        people_table = people_table.addfield(
            "date", lambda v: isodatetime(v["edited"]).strftime("%Y-%m-%d")
        )
        people_table = people_table.cutout(
            "films",
            "species",
            "vehicles",
            "starships",
            "edited",
            "created",
            "url",
            "homeworld",
        )
        people_table = people_table.rename("homeworld_name", "homeworld")

        collection = cls()
        with NamedTemporaryFile() as tmpfile:
            etl.tocsv(people_table, tmpfile.name)
            collection.file.save(f"{uuid.uuid4()}.csv", content=File(tmpfile))

        collection.save()
        return collection

    @classmethod
    def fetch_starwars_data(self):
        client = SWClient()
        people = client.get_people()
        homeworlds = client.get_homeworlds()
        return people, homeworlds

sd/swexplorer/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, RedirectView, DetailView

from swexplorer.models import Collection


class CollectionListView(ListView):
    template_name = "list.html"
    queryset = Collection.objects.all()


class CollectionDetailView(DetailView):
    template_name = "detail.html"
    queryset = Collection.objects.all()
    rows = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        etl = kwargs["object"].etl
        try:
            context["page"] = page = int(self.request.GET.get("page", 0))
        except ValueError:
            context["page"] = page = 0

        context["rows"] = etl.rowslice(page * self.rows, (page + 1) * self.rows)
        # TODO: Check if there is a next page and if not hide 'Next' button.
        return context


class CollectionCountView(DetailView):
    template_name = "count.html"
    queryset = Collection.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        etl = kwargs["object"].etl
        fields = self.request.GET.getlist("fields")
        # TODO: Check if `fields` are not empty.
        context["counter"] = etl.valuecounts(*fields)
        return context


class FetchCollectionView(RedirectView):
    url = reverse_lazy("swexplorer:list")

    def get(self, request, *args, **kwargs):
        Collection.get_collection()
        return super().get(request, *args, **kwargs)

sd/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Star Wars explorer {% block title %}{% endblock %}</title>
    <style>
        * {
            font-size: 12px;
            line-height: 1.5;
        }
    </style>
</head>
<body>
{% block body %}
{% block navbar %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Star Wars Explorer</a></li>
        {% block navbar-content %}{% endblock %}
    </ol>
</nav>
{% endblock %}
{% block content %}

{% endblock %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
-->
{% endblock %}
</body>
</html>

sd/templates/count.html
{% extends "detail.html" %}
{% block title %}{{block.super}} | Count{% endblock %}
{% block navbar-content %}
{{ block.super }}
<li class="breadcrumb-item active" aria-current="page"><a href="{{ object.get_absolute_url }}">Count</a></li>
{% endblock %}

{% block content %}
<table class="table table-striped table-hover">
    <thead>
    <tr>
        {% for field in counter|first|slice:":-1" %}
        <th scope="col">{{ field|title }}</th>
        {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for row in counter|slice:"1:" %}
    <tr>
        {% for col in row|slice:":-1" %}
        <th scope="row">{{ col }}</th>
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

sd/templates/detail.html
{% extends "list.html" %}
{% block title %}{{block.super}} | Detail #{{object.pk}}{% endblock %}
{% block navbar-content %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">#{{ object.pk }}</a></li>
{% endblock %}

{% block content %}
<form action="{% url 'swexplorer:count' object.pk %}" method="get">
    {% for field in rows|first %}
    <div class="form-check form-check-inline">

      <input class="form-check-input" type="checkbox" name="fields" id="id_{{field}}" value="{{field}}">
      <label class="form-check-label" for="id_{{field}}">{{field}}</label>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Value Count</button>
</form>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            {% for field in rows|first %}
            <th scope="col">{{ field|title }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for row in rows|slice:"1:" %}
        <tr>
            {% for col in row %}
            <th scope="row">{{ col }}</th>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
<a class="btn btn-warning" href="{% url "swexplorer:detail" object.pk %}?page={{page|add:1}}">Next</a>
{% endblock %}

sd/templates/list.html
{% extends "base.html" %}
{% block title %}{{block.super}} | List{% endblock %}
{% block navbar-content %}
<li class="breadcrumb-item"><a href="{% url 'swexplorer:list' %}">Collections</a></li>
{% endblock %}

{% block content %}
<form action="{% url 'swexplorer:fetch' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Fetch</button>
</form>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th scope="col">Date</th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <td><a href="{% url 'swexplorer:detail' object.pk %}">{{ object.created }}</a></td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="2">Empty</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}